"""create column car table

Revision ID: 2e48e6040e9d
Revises: 81c8235a1160
Create Date: 2024-05-30 22:09:23.636047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e48e6040e9d'
down_revision: Union[str, None] = '81c8235a1160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('name', sa.String(), nullable=True))
    op.add_column('cars', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('cars', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('cars', sa.Column('image', sa.String(), nullable=True))
    op.drop_index('ix_cars_make', table_name='cars')
    op.create_index(op.f('ix_cars_brand'), 'cars', ['brand'], unique=False)
    op.create_index(op.f('ix_cars_name'), 'cars', ['name'], unique=False)
    op.drop_column('cars', 'make')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('make', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_cars_name'), table_name='cars')
    op.drop_index(op.f('ix_cars_brand'), table_name='cars')
    op.create_index('ix_cars_make', 'cars', ['make'], unique=False)
    op.drop_column('cars', 'image')
    op.drop_column('cars', 'price')
    op.drop_column('cars', 'brand')
    op.drop_column('cars', 'name')
    # ### end Alembic commands ###
