"""Alter table add scription column

Revision ID: 9d872ad11b8f
Revises: 2e48e6040e9d
Create Date: 2024-05-30 22:25:05.898961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d872ad11b8f'
down_revision: Union[str, None] = '2e48e6040e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('d_alt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'd_alt')
    # ### end Alembic commands ###
